name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: docker-machine-driver-vcloud-director-linux-amd64.tgz
            asset_name: docker-machine-driver-vcloud-director-linux-amd64.tgz
          - os: windows-latest
            artifact_name: docker-machine-driver-vcloud-director.exe
            asset_name: docker-machine-driver-vcloud-director-windows-amd64
          - os: macos-latest
            artifact_name: docker-machine-driver-vcloud-director
            asset_name: docker-machine-driver-vcloud-director-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: go build
    - name: Create tar.gz
      if: matrix.os == 'ubuntu-latest'
      run: tar -czvf docker-machine-driver-vcloud-director-linux-amd64.tgz docker-machine-driver-vcloud-director
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
